services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.1
    networks:
      - main
    restart: always
  postgres:
    container_name: postgres
    image: postgres:15.3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - main
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  source:
    image: mirese:1
    command: sh -c "python manage.py migrate && gunicorn mapi.wsgi -b 0.0.0.0:8000"
    container_name: mirese
    volumes:
      - .:/src/
    depends_on:
      - postgres
      - rabbitmq
    expose:
      - "8000"
    networks:
      - main
    restart: always

  nginx:
    container_name: nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - source
    image: nginx:1.25.1
    networks:
      - main
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


networks:
  main:
volumes:
  postgres_data:



