# Generated by Django 4.2.2 on 2023-07-05 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreBaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('logo', models.FileField(upload_to='logo/')),
                ('store_status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فروشگاه خرید نان',
                'verbose_name_plural': 'فروشگاه های خرید نان',
            },
        ),
        migrations.CreateModel(
            name='ReadyOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.IntegerField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('bread_number', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نوبت در حال تحویل',
                'verbose_name_plural': 'نوبت های درحال تحویل',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.IntegerField(unique=True)),
                ('time', models.IntegerField()),
                ('waiting_time', models.IntegerField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('bread_number', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_order', to='orders.storebaker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نوبت ثبت شده',
                'verbose_name_plural': 'نوبت های ثبت شده',
            },
        ),
    ]
